#!/bin/bash
APPDIR="$(dirname "$(readlink -f "$0")")"
export GST_PLUGIN_PATH="${APPDIR}/usr/lib/gstreamer-1.0${GST_PLUGIN_PATH:+:$GST_PLUGIN_PATH}"
export GST_PLUGIN_SYSTEM_PATH="${APPDIR}/usr/lib/gstreamer-1.0"
export GST_REGISTRY_FORK="no"
export GST_REGISTRY="${APPDIR}/usr/lib/gstreamer-1.0/registry.bin"
export GST_PLUGIN_SCANNER="${APPDIR}/usr/libexec/gstreamer-1.0/gst-plugin-scanner"
export XDG_DATA_DIRS="${APPDIR}/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
exec "${APPDIR}/usr/bin/tunecraft" "$@"
